### ISSUE TITLE
version.properties  not found

### ISSUE THREAD

**Issue by theophany77** [igrek51/android-songbook#1]
Hi,

Being a newbie in Android and searching for a songbook, I found yours on Github.
When opening your project under Android Studio 2.1.3 (with Gradle 2.14.1), I have the following error :

> Error:(32, 0) Could not read version.properties!
> <a href="openFile:F:\android\android-songbook-master\android-songbook-master\app\build.gradle">Open File</a>

Where does it come from ?
Apparently, there is no "version.properties" file under the android-songbook-master file, along with the build.gradle
Is it normal ?

Thank you for your help.

Jean-michel ,France

**Comment by theophany77** [comment]
Hi,

I have updated the build.gradle by commenting the lines concerning the version.properties
Then I have initialized the following values :
        versionCode 1
        versionName "1.0"

The apk works now on my Samsung S3 4.4.4 and, when opening, it displays all the directories under root.
But I wonder what kind of files you use as a song book.
Moreover, I do not understand the language in the menu.

Thanks you.

Jean-michel

**Comment by igrek51** [comment]
Hey, thanks for reporting a bug.
The file "version.properties" was missing in git repository indeed. Actually I had this file on my disk but it was not added to git (to avoid conflicts, because it was automatically changing after every gradle build).
The missing file was added to app directory, and it should be fine now.

The example song book files are now included in release directory (look for SongBook-guitarDB-....zip).
Mostly there are Polish songs with chords, but not only (unfortunately some of them has only lyrics with no chords).
Adding new song book files is very easy because the file format is simple: the song lyrics is text (utf-8 or cp-1250) and the guitar chords is text enclosed by brackets, for example:
Lyrics, lyrics, ... [a F C G]
Another lyrics [C# f#]

In the menu there is only the Polish language now, but the English will should appear soon :)

Thanks,
looking forward to your feedback :)

**Comment by theophany77** [comment]
Hi !

Thank you very much for your quick answer.
The last version works properly now on my mobile.
How do you use the songbook ?
Do you put it anywhere on the mobile and access it through the songbook's
explorer ?
I guess I have to uncompress it and put the whole file on my mobile.
What is the difference between the Gitara file and the GuitarDB file ?

Thanks in advance.

Jean-michel

2016-09-13 23:54 GMT+02:00 igrek51 notifications@github.com:

**Comment by igrek51** [comment]
Now the English version has been released at last. It is now in the branch "master" and "en-lang".

SongBook is an application which shows the lyrics of songs with the guitar chords. While displaying songs the screen is always on, so you can use it while playing on guitar. You can also transpose the song to every different key (using transpose tools such as gestures to left/right or quick menu after clicking on screen).
Also you can turn on the autoscrolling mode, so you can play songs with long lyrics without need to scroll it manually while playing.
Generally, the application tries to help people playing songs on guitar.

To use the Guitar database ("GuitarDB" and "Gitara" means the same) you have to unzip the songbook DB content (SongBook-db-....zip) and put it anywhere on your mobile device. Next, choose by the SongBook application explorer the selected *.crd song file, and then enjoy the lyrics with the chords :)

**Comment by theophany77** [comment]
English version downloaded and installed.
Very nice job, all works perfectly.
I wonder if a download on internet of the last zip file triggered by a new choice in the menu would require too much work ?
Thank you very much. 
Jean-michel
